name: Node tests & Docker Image CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm cache clean --force 
    - run: yarn install
    - run: yarn jest
    - run: yarn build

  build:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: x280/snapchat-data-viewer
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
